# Site settings
title: "Thomas Harrington"
description: > 
  Write a description of your website here.

author: Thomas Harrington
email: tom@twh.works
twitter_username: 
github_username: twhworks

baseurl: "twh.works" # the subpath of your site, e.g. /blog
url: "https://twh.works/" # the base hostname & protocol for your site

google_analytics_id: 
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

